name: Deploy to Prod

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Release version'
        required: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Connect via SSH and Deploy
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.PROD_HOST }}
          username: ${{ secrets.PROD_USER }}
          key: ${{ secrets.PROD_SSH_KEY }}
          script: |
            docker pull cr.yandex/<registry-id>/app:${{ github.event.inputs.version }}_latest
            docker stop app || true && docker rm app || true
            docker run -d -p 80:3000 --name app cr.yandex/<registry-id>/app:${{ github.event.inputs.version }}_latest
